[header]
name   = "Eruption"
bounds = { x = 150, y = 0, z = 15, width = 450, height = 800, depth = 50 }

[[layer]]
# Sky
position = { x = 0, y = 134, z = 0 }
frames = [
  { sheet = 1, sprite = 0, wait = 10 },
]

[[layer]]
# Ground
position = { x = 0, y = 0, z = 0 }
frames = [
  { sheet = 0, sprite = 0, wait = 10 },
  { sheet = 0, sprite = 1, wait = 10 },
  { sheet = 0, sprite = 2, wait = 10 },
]
