# Hold attack to charge.
charge_limit = 40 # Max charge points to store.
charge_delay = 1  # Number of ticks per charge increment.
charge_use_mode = "all"

# charge_retention_mode = "forever"
charge_retention_mode = "never"
# charge_retention_mode = { lossy = { delay = 1 } }
# charge_retention_mode = { reset = { delay = 60 } }

[sequences.stand]
  [sequences.stand.transitions.press_attack]
    next = "stand_attack_0"

  [sequences.stand.transitions.press_jump]
    next = "jump"

  [[sequences.stand.transitions.release_attack]]
    next = "dazed" # placeholder for strong blast
    requirements = [{ charge = 40 }]

  [[sequences.stand.transitions.release_attack]]
    next = "stand_attack_1"
    requirements = [{ charge = 13 }]

  [[sequences.stand.frames]]
    wait = 8
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.stand_attack_0]
  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.stand_attack_0.frames.spawns]]
      object = "default/buster_shot_weak"
      position = [22, 33, 0]
      velocity = [5, 0, 0]

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [sequences.stand_attack_0.frames.transitions]
      press_attack = "stand_attack_0"

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [sequences.stand_attack_0.frames.transitions]
      press_attack = "stand_attack_0"

  [[sequences.stand_attack_0.frames]]
    wait = 1
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [sequences.stand_attack_0.frames.transitions]
      press_attack = "stand_attack_0"

[sequences.stand_attack_1]
  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.stand_attack_1.frames.spawns]]
      object = "default/buster_shot_mid"
      position = [22, 33, 0]
      velocity = [6, 0, 0]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.dazed]
  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.dazed.frames.spawns]]
      object = "default/buster_shot_strong"
      position = [22, 33, 0]
      velocity = [7, 0, 0]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dazed.frames]]
    wait = 2
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.walk]
  [sequences.walk.transitions.press_attack]
    next = "stand_attack_0"

  [sequences.walk.transitions.press_jump]
    next = "jump"

  [sequences.walk.transitions.fallback]
    next = "stand"
    requirements = [{ input_dir_x = "none" }, { input_dir_z = "none" }]

  [[sequences.walk.transitions.release_attack]]
    next = "dazed" # placeholder for strong blast
    requirements = [{ charge = 40 }]

  [[sequences.walk.transitions.release_attack]]
    next = "stand_attack_1"
    requirements = [{ charge = 13 }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.run]
  [[sequences.run.frames]]
    wait = 6
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.run.frames]]
    wait = 6
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.run.frames]]
    wait = 6
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.run.frames]]
    wait = 6
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.run_stop]
  [[sequences.run_stop.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.dodge]
  [[sequences.dodge.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }

[sequences.jump]
  [[sequences.jump.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.jump.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.jump_off]
  [[sequences.jump_off.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.jump_ascend]
  [[sequences.jump_ascend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    transitions = { hold_attack = "jump_attack" }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.jump_descend]
  [[sequences.jump_descend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    transitions = { hold_attack = "jump_attack" }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.jump_descend_land]
  [[sequences.jump_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.jump_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.jump_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.jump_attack]
  [[sequences.jump_attack.frames]]
    wait = 5
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.jump_attack.frames.interactions]]
      hit = { repeat_delay = 17, hp_damage = 10 }
      bounds = [{ box = { x = 37, y = 46, w = 21, h = 24 } }]

  [[sequences.jump_attack.frames]]
    wait = 11
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.jump_attack.frames.interactions]]
      hit = { repeat_delay = 17, hp_damage = 10 }
      bounds = [{ box = { x = 37, y = 46, w = 21, h = 24 } }]

# Dashing
[sequences.dash_forward]
  [[sequences.dash_forward.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]
    transitions = { press_attack = "dash_attack" }

[sequences.dash_forward_ascend]
  [[sequences.dash_forward_ascend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]
    transitions = { press_attack = "dash_attack" }

[sequences.dash_forward_descend]
  [[sequences.dash_forward_descend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]
    transitions = { press_attack = "dash_attack" }

[sequences.dash_back]
  [[sequences.dash_back.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [
      { box = { x = 20, y = 12, w = 26, h = 43 } },
      { box = { x = 35, y = 40, w = 20, h = 26 } },
    ]

[sequences.dash_back_ascend]
  [[sequences.dash_back_ascend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [
      { box = { x = 20, y = 12, w = 26, h = 43 } },
      { box = { x = 35, y = 40, w = 20, h = 26 } },
    ]

[sequences.dash_back_descend]
  [[sequences.dash_back_descend.frames]]
    wait = 1
    sprite = { sheet = 0, index = 0 }
    body = [
      { box = { x = 20, y = 12, w = 26, h = 43 } },
      { box = { x = 35, y = 40, w = 20, h = 26 } },
    ]

[sequences.dash_descend_land]
  [[sequences.dash_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dash_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dash_descend_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.dash_attack]
  [[sequences.dash_attack.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dash_attack.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.dash_attack.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.dash_attack.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 10 }
      bounds = [{ box = { x = 38, y = 31, w = 25, h = 20 } }]

  [[sequences.dash_attack.frames]]
    wait = 9
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

    [[sequences.dash_attack.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 10 }
      bounds = [{ box = { x = 38, y = 31, w = 25, h = 20 } }]

[sequences.flinch_0]
  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.flinch_1]
  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

# Fall when knocked down.
[sequences.fall_forward_ascend]
  [[sequences.fall_forward_ascend.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.fall_forward_descend]
  [[sequences.fall_forward_descend.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.fall_forward_descend.frames]]
    wait = 4
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.fall_forward_descend.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.fall_forward_land]
  [[sequences.fall_forward_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

  [[sequences.fall_forward_land.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]

[sequences.lie_face_down]
  [[sequences.lie_face_down.frames]]
    wait = 120
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 16, y = 10, w = 28, h = 53 } }]
