[sequences.stand]
  [[sequences.stand.frames]]
    wait = 8
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.stand.frames]]
    wait = 8
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.stand.frames]]
    wait = 8
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.stand.frames]]
    wait = 8
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

[sequences.stand_attack_0]
  [[sequences.stand_attack_0.frames]]
    wait = 2
    sprite = { sheet = 2, index = 0 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

  [[sequences.stand_attack_0.frames]]
    wait = 2
    sprite = { sheet = 2, index = 1 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

    [[sequences.stand_attack_0.frames.interactions]]
      hit = { repeat_delay = 9, hp_damage = 7 }
      bounds = [{ box = { x = 50, y = 32, w = 17, h = 18 } }]

  [[sequences.stand_attack_0.frames]]
    wait = 3
    sprite = { sheet = 2, index = 2 }
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    transitions = { press_attack = "stand_attack_1" }

    [[sequences.stand_attack_0.frames.interactions]]
      hit = { repeat_delay = 9, hp_damage = 7 }
      bounds = [{ box = { x = 50, y = 30, w = 22, h = 18 } }]

[sequences.stand_attack_1]
  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 2, index = 3 }
    body = [{ box = { x = 25, y = 91, w = 31, h = 68 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 2
    sprite = { sheet = 2, index = 4 }
    body = [{ box = { x = 25, y = 91, w = 31, h = 68 } }]

    [[sequences.stand_attack_1.frames.interactions]]
      hit = { repeat_delay = 9, hp_damage = 7 }
      bounds = [{ box = { x = 27, y = 35, w = 25, h = 13 } }]

  [[sequences.stand_attack_1.frames]]
    wait = 3
    sprite = { sheet = 2, index = 5 }
    body = [{ box = { x = 25, y = 91, w = 31, h = 68 } }]

    [[sequences.stand_attack_1.frames.interactions]]
      hit = { repeat_delay = 9, hp_damage = 7 }
      bounds = [{ box = { x = 31, y = 34, w = 23, h = 16 } }]

[sequences.walk]
  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 25, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 105, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 6 }
    body = [{ box = { x = 185, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 7 }
    body = [{ box = { x = 265, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 6 }
    body = [{ box = { x = 185, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

  [[sequences.walk.frames]]
    wait = 3
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 105, y = 93, w = 35, h = 66 } }]
    transitions = { press_attack = "stand_attack_0", press_jump = "jump" }

[sequences.run]
  [[sequences.run.frames]]
    wait = 4
    sprite = { sheet = 0, index =  8 }
    body = [{ box = { x = 25, y = 177, w = 31, h = 62 } }]

  [[sequences.run.frames]]
    wait = 4
    sprite = { sheet = 0, index =  9 }
    body = [{ box = { x = 105, y = 177, w = 31, h = 62 } }]

  [[sequences.run.frames]]
    wait = 4
    sprite = { sheet = 0, index = 10 }
    body = [{ box = { x = 185, y = 177, w = 31, h = 62 } }]

  [[sequences.run.frames]]
    wait = 4
    sprite = { sheet = 0, index =  9 }
    body = [{ box = { x = 265, y = 177, w = 31, h = 62 } }]

[sequences.run_stop]
  frames = [{ wait = 3, sprite = { sheet = 0, index = 11 } }]

[sequences.dodge]
  frames = [
    { wait = 4, sprite = { sheet = 0, index = 20 } },
    { wait = 4, sprite = { sheet = 0, index = 21 } },
    { wait = 4, sprite = { sheet = 0, index = 22 } },
    { wait = 4, sprite = { sheet = 0, index = 20 } },
  ]

[sequences.jump]
  frames = [
    { wait = 2, sprite = { sheet = 0, index = 12 } },
    { wait = 1, sprite = { sheet = 0, index = 13 } },
  ]

[sequences.jump_off]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 14 } }]

[sequences.jump_ascend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 14 } }]

[sequences.jump_descend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 14 } }]

[sequences.jump_descend_land]
  frames = [
    { wait = 0, sprite = { sheet = 0, index = 12 } },
    { wait = 0, sprite = { sheet = 0, index = 13 } },
    { wait = 1, sprite = { sheet = 0, index = 12 } },
  ]

# Dashing
[sequences.dash_forward]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 16 } }]

[sequences.dash_forward_ascend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 16 } }]

[sequences.dash_forward_descend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 17 } }]

[sequences.dash_back]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 18 } }]

[sequences.dash_back_ascend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 18 } }]

[sequences.dash_back_descend]
  frames = [{ wait = 1, sprite = { sheet = 0, index = 19 } }]

[sequences.dash_descend_land]
  frames = [
    { wait = 0, sprite = { sheet = 0, index = 12 } },
    { wait = 0, sprite = { sheet = 0, index = 13 } },
    { wait = 1, sprite = { sheet = 0, index = 12 } },
  ]

# Flinch when character is hit.
#
# * `flinch_0`: Got hit when on ground.
# * `flinch_1`: Got hit when on ground - alternate sequence.
[sequences.flinch_0]
  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 3, index = 24 }
    body = [{ box = { x = 22, y = 22, w = 32, h = 57 } }]

  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 3, index = 25 }
    body = [{ box = { x = 22, y = 23, w = 29, h = 56 } }]

  [[sequences.flinch_0.frames]]
    wait = 2
    sprite = { sheet = 3, index = 24 }
    body = [{ box = { x = 22, y = 22, w = 32, h = 57 } }]

[sequences.flinch_1]
  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 3, index = 26 }
    body = [{ box = { x = 20, y = 17, w = 31, h = 62 } }]

  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 3, index = 27 }
    body = [{ box = { x = 26, y = 19, w = 32, h = 60 } }]

  [[sequences.flinch_1.frames]]
    wait = 2
    sprite = { sheet = 3, index = 26 }
    body = [{ box = { x = 20, y = 17, w = 31, h = 62 } }]

# Fall when knocked down.
[sequences.fall_forward_ascend]
  [[sequences.fall_forward_ascend.frames]]
    wait = 2
    sprite = { sheet = 3, index = 6 }
    # body = [
    #   { box = { x = 21, y = 92, w = 21, h = 28 } },
    #   { box = { x = 38, y = 32, w = 23, h = 27 } },
    # ]

[sequences.fall_forward_descend]
  [[sequences.fall_forward_descend.frames]]
    wait = 3
    sprite = { sheet = 3, index = 7 }
    # body = [
    #   { box = { x = 26, y = 89, w = 27, h = 27 } },
    #   { box = { x = 98, y = 36, w = 25, h = 23 } },
    # ]

  [[sequences.fall_forward_descend.frames]]
    wait = 4
    sprite = { sheet = 3, index = 8 }
    # body = [
    #   { box = { x = 30, y = 92, w = 21, h = 19 } },
    #   { box = { x = 18, y = 29, w = 36, h = 22 } },
    # ]

  [[sequences.fall_forward_descend.frames]]
    wait = 2
    sprite = { sheet = 3, index = 9 }
    # body = [{ box = { x = 17, y = 30, w = 45, h = 28 } }]

[sequences.fall_forward_land]
  [[sequences.fall_forward_land.frames]]
    wait = 2
    sprite = { sheet = 3, index = 10 }
    # body = [
    #   { box = { x = 13, y = 57, w = 31, h = 20 } },
    #   { box = { x = 44, y = 40, w = 21, h = 27 } },
    # ]

  [[sequences.fall_forward_land.frames]]
    wait = 2
    sprite = { sheet = 3, index = 11 }
    # body = [
    #   { box = { x = 13, y = 43, w = 26, h = 32 } },
    #   { box = { x = 39, y = 54, w = 22, h = 37 } },
    # ]

[sequences.lie_face_down]
  [[sequences.lie_face_down.frames]]
    wait = 30
    sprite = { sheet = 3, index = 10 }
    # body = [
    #   { box = { x = 13, y = 57, w = 31, h = 20 } },
    #   { box = { x = 44, y = 40, w = 21, h = 27 } },
    # ]
