[sequences.stand]
  frames = [
    { sheet = 0, sprite = 0, wait = 5 },
    { sheet = 0, sprite = 1, wait = 5 },
    { sheet = 0, sprite = 2, wait = 5 },
    { sheet = 0, sprite = 3, wait = 5 },
  ]

[sequences.stand_attack]
  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 0
    wait = 1

  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 1
    wait = 1

  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 2
    wait = 1

[sequences.walk]
  frames = [
    { sheet = 0, sprite = 4, wait = 3 },
    { sheet = 0, sprite = 5, wait = 3 },
    { sheet = 0, sprite = 6, wait = 3 },
    { sheet = 0, sprite = 7, wait = 3 },
    { sheet = 0, sprite = 6, wait = 3 },
    { sheet = 0, sprite = 5, wait = 3 },
  ]

[sequences.run]
  frames = [
    { sheet = 0, sprite =  8, wait = 4 },
    { sheet = 0, sprite =  9, wait = 4 },
    { sheet = 0, sprite = 10, wait = 4 },
    { sheet = 0, sprite =  9, wait = 4 },
  ]

[sequences.run_stop]
  frames = [{ sheet = 0, sprite = 11, wait = 3 }]

[sequences.jump]
  frames = [
    { sheet = 0, sprite = 12, wait = 2 },
    { sheet = 0, sprite = 13, wait = 1 },
  ]

[sequences.jump_off]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_ascend]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_descend]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_descend_land]
  frames = [
    { sheet = 0, sprite = 12, wait = 0 },
    { sheet = 0, sprite = 13, wait = 0 },
    { sheet = 0, sprite = 12, wait = 1 },
  ]
