[sequences.stand]
  [[sequences.stand.frames]]
    wait = 5
    sheet = 0
    sprite = 0
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

  [[sequences.stand.frames]]
    wait = 5
    sheet = 0
    sprite = 1
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

  [[sequences.stand.frames]]
    wait = 5
    sheet = 0
    sprite = 2
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

  [[sequences.stand.frames]]
    wait = 5
    sheet = 0
    sprite = 3
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

[sequences.stand_attack]
  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 0
    wait = 1
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]

  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 1
    wait = 1
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    interactions = [
      { physical = { bounds = [{ box = { x = 50, y = 32, w = 17, h = 18 } }], hp_damage = 20 } },
    ]

  [[sequences.stand_attack.frames]]
    sheet = 2
    sprite = 2
    wait = 1
    body = [{ box = { x = 25, y = 11, w = 31, h = 68 } }]
    interactions = [
      { physical = { bounds = [{ box = { x = 50, y = 30, w = 22, h = 18 } }], hp_damage = 20 } },
    ]

[sequences.walk]
  frames = [
    { sheet = 0, sprite = 4, wait = 3 },
    { sheet = 0, sprite = 5, wait = 3 },
    { sheet = 0, sprite = 6, wait = 3 },
    { sheet = 0, sprite = 7, wait = 3 },
    { sheet = 0, sprite = 6, wait = 3 },
    { sheet = 0, sprite = 5, wait = 3 },
  ]

[sequences.run]
  frames = [
    { sheet = 0, sprite =  8, wait = 4 },
    { sheet = 0, sprite =  9, wait = 4 },
    { sheet = 0, sprite = 10, wait = 4 },
    { sheet = 0, sprite =  9, wait = 4 },
  ]

[sequences.run_stop]
  frames = [{ sheet = 0, sprite = 11, wait = 3 }]

[sequences.jump]
  frames = [
    { sheet = 0, sprite = 12, wait = 2 },
    { sheet = 0, sprite = 13, wait = 1 },
  ]

[sequences.jump_off]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_ascend]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_descend]
  frames = [{ sheet = 0, sprite = 14, wait = 1 }]

[sequences.jump_descend_land]
  frames = [
    { sheet = 0, sprite = 12, wait = 0 },
    { sheet = 0, sprite = 13, wait = 0 },
    { sheet = 0, sprite = 12, wait = 1 },
  ]

# Flinch when character is hit.
#
# * `flinch_0`: Got hit when on ground.
# * `flinch_1`: Got hit when on ground - alternate sequence.
[sequences.flinch_0]
  [[sequences.flinch_0.frames]]
    sheet = 3
    sprite = 24
    wait = 2
    body = [{ box = { x = 22, y = 342, w = 32, h = 57 } }]

  [[sequences.flinch_0.frames]]
    sheet = 3
    sprite = 25
    wait = 2
    body = [{ box = { x = 102, y = 343, w = 29, h = 56 } }]

  [[sequences.flinch_0.frames]]
    sheet = 3
    sprite = 24
    wait = 2
    body = [{ box = { x = 22, y = 342, w = 32, h = 57 } }]

[sequences.flinch_1]
  [[sequences.flinch_1.frames]]
    sheet = 3
    sprite = 26
    wait = 2
    body = [{ box = { x = 180, y = 337, w = 31, h = 62 } }]

  [[sequences.flinch_1.frames]]
    sheet = 3
    sprite = 27
    wait = 2
    body = [{ box = { x = 266, y = 339, w = 32, h = 60 } }]

  [[sequences.flinch_1.frames]]
    sheet = 3
    sprite = 26
    wait = 2
    body = [{ box = { x = 180, y = 337, w = 31, h = 62 } }]

# Fall when knocked down.
[sequences.fall_forward_ascend]
  [[sequences.fall_forward_ascend.frames]]
    sheet = 3
    sprite = 6
    wait = 2
    body = [
      { box = { x = 21, y = 92, w = 21, h = 28 } },
      { box = { x = 38, y = 112, w = 23, h = 27 } },
    ]

[sequences.fall_forward_descend]
  [[sequences.fall_forward_descend.frames]]
    sheet = 3
    sprite = 7
    wait = 3
    body = [
      { box = { x = 106, y = 89, w = 27, h = 27 } },
      { box = { x = 98, y = 116, w = 25, h = 23 } },
    ]

  [[sequences.fall_forward_descend.frames]]
    sheet = 3
    sprite = 8
    wait = 4
    body = [
      { box = { x = 190, y = 92, w = 21, h = 19 } },
      { box = { x = 178, y = 109, w = 36, h = 22 } },
    ]

  [[sequences.fall_forward_descend.frames]]
    sheet = 3
    sprite = 9
    wait = 2
    body = [{ box = { x = 257, y = 110, w = 45, h = 28 } }]

[sequences.fall_forward_land]
  [[sequences.fall_forward_land.frames]]
    sheet = 3
    sprite = 10
    wait = 2
    body = [
      { box = { x = 333, y = 137, w = 31, h = 20 } },
      { box = { x = 364, y = 120, w = 21, h = 27 } },
    ]

  [[sequences.fall_forward_land.frames]]
    sheet = 3
    sprite = 11
    wait = 2
    body = [
      { box = { x = 413, y = 123, w = 26, h = 32 } },
      { box = { x = 439, y = 134, w = 22, h = 37 } },
    ]

[sequences.lie_face_down]
  [[sequences.lie_face_down.frames]]
    sheet = 3
    sprite = 10
    wait = 30
    body = [
      { box = { x = 333, y = 137, w = 31, h = 20 } },
      { box = { x = 364, y = 120, w = 21, h = 27 } },
    ]
