[[sheets]]
  # 0
  path         = "heat_movement.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 6
  column_count = 4
  offsets = [
    { x =  35, y =  79 }, #  0
    { x = 115, y =  79 }, #  1
    { x = 195, y =  79 }, #  2
    { x = 275, y =  79 }, #  3
    { x =  35, y = 159 }, #  4
    { x = 115, y = 159 }, #  5
    { x = 195, y = 159 }, #  6
    { x = 275, y = 159 }, #  7
    { x =  35, y = 239 }, #  8
    { x = 115, y = 239 }, #  9
    { x = 195, y = 239 }, # 10
    { x = 275, y = 239 }, # 11
    { x =  35, y = 319 }, # 12
    { x = 115, y = 319 }, # 13
    { x = 195, y = 319 }, # 14
    { x = 275, y = 319 }, # 15
    { x =  35, y = 399 }, # 16
    { x = 115, y = 399 }, # 17
    { x = 195, y = 399 }, # 18
    { x = 275, y = 399 }, # 19
    { x =  35, y = 479 }, # 20
    { x = 115, y = 479 }, # 21
    { x = 195, y = 479 }, # 22
    { x = 275, y = 479 }, # 23
  ]

[[sheets]]
  # 1
  path         = "heat_defense.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 2
  column_count = 3
  offsets = [
    { x =  35, y =  79 }, # 0
    { x = 115, y =  79 }, # 1
    { x = 195, y =  79 }, # 2
    { x =  35, y = 159 }, # 3
    { x = 115, y = 159 }, # 4
    { x = 195, y = 159 }, # 5
  ]

[[sheets]]
  # 2
  path         = "heat_punch.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 4
  column_count = 3
  offsets = [
    { x =  35, y =  79 }, #  0
    { x = 115, y =  79 }, #  1
    { x = 195, y =  79 }, #  2
    { x =  35, y = 159 }, #  3
    { x = 115, y = 159 }, #  4
    { x = 195, y = 159 }, #  5
    { x =  36, y = 233 }, #  6
    { x = 116, y = 233 }, #  7
    { x = 195, y = 239 }, #  8
    { x =  35, y = 319 }, #  9
    { x = 115, y = 319 }, # 10
    { x = 195, y = 319 }, # 11
  ]

[[sheets]]
  # 3
  path         = "heat_interaction.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 5
  column_count = 6
  offsets = [
    { x =  34, y =  63 }, #  0
    { x = 108, y =  47 }, #  1
    { x = 197, y =  36 }, #  2
    { x = 280, y =  45 }, #  3
    { x = 358, y =  69 }, #  4
    { x = 436, y =  68 }, #  5

    { x =  44, y = 143 }, #  6
    { x = 118, y = 141 }, #  7
    { x = 198, y = 138 }, #  8
    { x = 274, y = 138 }, #  9
    { x = 356, y = 156 }, # 10
    { x = 433, y = 154 }, # 11

    { x =  29, y = 233 }, # 12
    { x = 116, y = 202 }, # 13
    { x =   0, y =   0 }, # 14
    { x = 277, y = 202 }, # 15
    { x = 359, y = 227 }, # 16
    { x =   0, y =   0 }, # 17

    { x =  39, y = 313 }, # 18
    { x = 120, y = 312 }, # 19
    { x = 195, y = 313 }, # 20
    { x = 273, y = 318 }, # 21
    { x = 352, y = 318 }, # 22
    { x = 433, y = 318 }, # 23

    { x =  35, y = 398 }, # 24
    { x = 114, y = 398 }, # 25
    { x = 192, y = 398 }, # 26
    { x = 282, y = 398 }, # 27
    { x = 358, y = 398 }, # 28
    { x = 440, y = 398 }, # 29
  ]
