[[sheets]]
  # 0
  path         = "heat_movement.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 6
  column_count = 4
  offsets = [
    { x =  35, y =  79 }, #  0
    { x = 115, y =  79 }, #  1
    { x = 195, y =  79 }, #  2
    { x = 275, y =  79 }, #  3
    { x =  35, y = 159 }, #  4
    { x = 115, y = 159 }, #  5
    { x = 195, y = 159 }, #  6
    { x = 275, y = 159 }, #  7
    { x =  35, y = 239 }, #  8
    { x = 115, y = 239 }, #  9
    { x = 195, y = 239 }, # 10
    { x = 275, y = 239 }, # 11
    { x =  35, y = 319 }, # 12
    { x = 115, y = 319 }, # 13
    { x = 195, y = 319 }, # 14
    { x = 275, y = 319 }, # 15
    { x =  35, y = 399 }, # 16
    { x = 115, y = 399 }, # 17
    { x = 195, y = 399 }, # 18
    { x = 275, y = 399 }, # 19
    { x =  35, y = 479 }, # 20
    { x = 115, y = 479 }, # 21
    { x = 195, y = 479 }, # 22
    { x = 275, y = 479 }, # 23
  ]

[[sheets]]
  # 1
  path         = "heat_defense.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 2
  column_count = 3
  offsets = [
    { x =  35, y =  79 }, # 0
    { x = 115, y =  79 }, # 1
    { x = 195, y =  79 }, # 2
    { x =  35, y = 159 }, # 3
    { x = 115, y = 159 }, # 4
    { x = 195, y = 159 }, # 5
  ]

[[sheets]]
  # 2
  path         = "heat_punch.png"
  sprite_w     = 79
  sprite_h     = 79
  row_count    = 1
  column_count = 3
  offsets = [
    { x =  35, y =  79 }, #  0
    { x = 115, y =  79 }, #  1
    { x = 195, y =  79 }, #  2
    { x = 275, y =  79 }, #  3
  ]
