[sequences.hover]
  [[sequences.hover.frames]]
    wait = 4
    sprite = { sheet = 0, index = 0 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 15, stun = 90 }
      bounds = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

  [[sequences.hover.frames]]
    wait = 4
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 15, stun = 90 }
      bounds = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

[sequences.hit]
  next = "delete"

  [[sequences.hit.frames]]
    wait = 1
    sprite = { sheet = 0, index = 2 }

  [[sequences.hit.frames]]
    wait = 1
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

  [[sequences.hit.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

  [[sequences.hit.frames]]
    wait = 1
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

[sequences.hitting]
  next = "delete"

  [[sequences.hitting.frames]]
    wait = 1
    sprite = { sheet = 0, index = 2 }

  [[sequences.hitting.frames]]
    wait = 1
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

  [[sequences.hitting.frames]]
    wait = 1
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]

  [[sequences.hitting.frames]]
    wait = 1
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 15, y = 6, w = 39, h = 21 } }]
