[sequences.hover]
  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 0 }

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 1 }
    body = [{ box = { x = 25, y = 10, w = 16, h = 11 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 25, y = 10, w = 16, h = 11 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 2 }
    body = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 3 }
    body = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 4 }
    body = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 5 }
    body = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 21, y = 8, w = 23, h = 16 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 6 }
    body = [{ box = { x = 20, y = 10, w = 26, h = 13 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 20, y = 10, w = 26, h = 13 } }]

  [[sequences.hover.frames]]
    wait = 2
    sprite = { sheet = 0, index = 7 }
    body = [{ box = { x = 20, y = 10, w = 26, h = 13 } }]

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 20, stun = 100 }
      bounds = [{ box = { x = 20, y = 10, w = 26, h = 13 } }]

[sequences.hit]
  next = "delete"

  [[sequences.hit.frames]]
    wait = 2
    sprite = { sheet = 0, index = 8 }

  [[sequences.hit.frames]]
    wait = 2
    sprite = { sheet = 0, index = 9 }

  [[sequences.hit.frames]]
    wait = 2
    sprite = { sheet = 0, index = 10 }

  [[sequences.hit.frames]]
    wait = 2
    sprite = { sheet = 0, index = 11 }

[sequences.hitting]
  next = "delete"

  [[sequences.hitting.frames]]
    wait = 2
    sprite = { sheet = 0, index = 8 }

  [[sequences.hitting.frames]]
    wait = 2
    sprite = { sheet = 0, index = 9 }

  [[sequences.hitting.frames]]
    wait = 2
    sprite = { sheet = 0, index = 10 }

  [[sequences.hitting.frames]]
    wait = 2
    sprite = { sheet = 0, index = 11 }
