# Startup sequence, pending arbitrary sequence IDs
[sequences.hover]
  next = "hit"

  [[sequences.hover.frames]]
    wait = 3
    sprite = { sheet = 0, index = 0 }

  [[sequences.hover.frames]]
    wait = 3
    sprite = { sheet = 0, index = 1 }

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 26, y = 23, w = 13, h = 18 } }]

  [[sequences.hover.frames]]
    wait = 3
    sprite = { sheet = 0, index = 2 }

    [[sequences.hover.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 21, y = 18, w = 24, h = 27 } }]

# Hijacking the `hit` sequence as flying
[sequences.hit]
  next = "repeat"

  [[sequences.hit.frames]]
    wait = 4
    sprite = { sheet = 0, index = 3 }

    [[sequences.hit.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 17, y = 15, w = 30, h = 31 } }]

  [[sequences.hit.frames]]
    wait = 4
    sprite = { sheet = 0, index = 4 }

    [[sequences.hit.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 17, y = 15, w = 30, h = 31 } }]

  [[sequences.hit.frames]]
    wait = 4
    sprite = { sheet = 0, index = 5 }

    [[sequences.hit.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 17, y = 15, w = 30, h = 31 } }]

[sequences.hitting]
  next = "hit"

  [[sequences.hitting.frames]]
    wait = 3
    sprite = { sheet = 0, index = 5 }

    [[sequences.hitting.frames.interactions]]
      hit = { repeat_delay = 20, hp_damage = 40, stun = 120 }
      bounds = [{ box = { x = 17, y = 15, w = 30, h = 31 } }]
