[[sheets]]
  # 0
  path         = "buster_shot_strong.png"
  sprite_w     = 63
  sprite_h     = 63
  row_count    = 2
  column_count = 3
  offsets = [
    { x =  32, y = 32 }, # 0
    { x =  96, y = 32 }, # 1
    { x = 160, y = 32 }, # 2
    { x =  32, y = 96 }, # 3
    { x =  96, y = 96 }, # 4
    { x = 160, y = 96 }, # 5
  ]
